# Generated by Django 5.2.1 on 2025-05-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='users/')),
                ('description', models.TextField()),
                ('dateToRegister', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
