# Generated by Django 5.2.1 on 2025-05-20 14:01

import user_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_app.models.UserManager()),
            ],
        ),
    ]
