# Generated by Django 5.2.1 on 2025-05-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_to_register',
        ),
    ]
